# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5448:5432
    environment:
      POSTGRES_ADMIN_PASSWORD: tfpc3
      POSTGRES_PASSWORD: tfpc3
      POSTGRES_USER: tfpc3
      POSTGRES_DB: tfpc3